/**
 * Fyn - API
 * The Fyn application API
 *
 * OpenAPI spec version: 0.1.3
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AccountsApi", () => {
  let instance: api.AccountsApi
  beforeEach(function() {
    instance = new api.AccountsApi(config)
  });

  test("accountsControllerCreateV1", () => {
    const body: api.CreateAccountDto = undefined
    return expect(instance.accountsControllerCreateV1(body, {})).resolves.toBe(null)
  })
  test("accountsControllerDeleteV1", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.accountsControllerDeleteV1(id, {})).resolves.toBe(null)
  })
  test("accountsControllerGetMeV1", () => {
    return expect(instance.accountsControllerGetMeV1({})).resolves.toBe(null)
  })
  test("accountsControllerGetV1", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.accountsControllerGetV1(id, {})).resolves.toBe(null)
  })
  test("accountsControllerListV1", () => {
    const page: number = 56
    const per_page: number = 56
    const search: string = "search_example"
    return expect(instance.accountsControllerListV1(page, per_page, search, {})).resolves.toBe(null)
  })
  test("accountsControllerUpdateMeV1", () => {
    const body: api.UpdateAccountDto = undefined
    return expect(instance.accountsControllerUpdateMeV1(body, {})).resolves.toBe(null)
  })
  test("accountsControllerUpdateV1", () => {
    const body: api.UpdateAccountDto = undefined
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.accountsControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

describe("ActiveSearchesApi", () => {
  let instance: api.ActiveSearchesApi
  beforeEach(function() {
    instance = new api.ActiveSearchesApi(config)
  });

  test("activeSearchesControllerAllOfMeV1", () => {
    return expect(instance.activeSearchesControllerAllOfMeV1({})).resolves.toBe(null)
  })
  test("activeSearchesControllerAllOfStudentV1", () => {
    const student_id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.activeSearchesControllerAllOfStudentV1(student_id, {})).resolves.toBe(null)
  })
  test("activeSearchesControllerCreateForMeV1", () => {
    const body: api.SearchPredicates = undefined
    return expect(instance.activeSearchesControllerCreateForMeV1(body, {})).resolves.toBe(null)
  })
  test("activeSearchesControllerCreateV1", () => {
    const body: api.SearchPredicates = undefined
    const student_id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.activeSearchesControllerCreateV1(body, student_id, {})).resolves.toBe(null)
  })
  test("activeSearchesControllerEditV1", () => {
    const body: api.SearchPredicates = undefined
    const id: number = 56
    return expect(instance.activeSearchesControllerEditV1(body, id, {})).resolves.toBe(null)
  })
  test("activeSearchesControllerFindV1", () => {
    const id: number = 1.2
    return expect(instance.activeSearchesControllerFindV1(id, {})).resolves.toBe(null)
  })
})

describe("ActivityDomainsApi", () => {
  let instance: api.ActivityDomainsApi
  beforeEach(function() {
    instance = new api.ActivityDomainsApi(config)
  });

  test("activityDomainsControllerCreateV1", () => {
    const body: api.CreateActivityDomainDto = undefined
    return expect(instance.activityDomainsControllerCreateV1(body, {})).resolves.toBe(null)
  })
  test("activityDomainsControllerFindAllV1", () => {
    const page: number = 56
    const limit: number = 56
    const query: string = "query_example"
    return expect(instance.activityDomainsControllerFindAllV1(page, limit, query, {})).resolves.toBe(null)
  })
  test("activityDomainsControllerFindOneV1", () => {
    const id: number = 1.2
    return expect(instance.activityDomainsControllerFindOneV1(id, {})).resolves.toBe(null)
  })
  test("activityDomainsControllerRemoveV1", () => {
    const id: number = 1.2
    return expect(instance.activityDomainsControllerRemoveV1(id, {})).resolves.toBe(null)
  })
  test("activityDomainsControllerUpdateV1", () => {
    const body: api.UpdateActivityDomainDto = undefined
    const id: number = 1.2
    return expect(instance.activityDomainsControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

describe("AppApi", () => {
  let instance: api.AppApi
  beforeEach(function() {
    instance = new api.AppApi(config)
  });

  test("appControllerGetPingV1", () => {
    const only: string = "only_example"
    return expect(instance.appControllerGetPingV1(only, {})).resolves.toBe(null)
  })
})

describe("ApplicationsApi", () => {
  let instance: api.ApplicationsApi
  beforeEach(function() {
    instance = new api.ApplicationsApi(config)
  });

  test("applicationsControllerCreateV1", () => {
    const body: api.CreateApplicationDto = undefined
    const job_id: string = "job_id_example"
    return expect(instance.applicationsControllerCreateV1(body, job_id, {})).resolves.toBe(null)
  })
  test("applicationsControllerFindAllV1", () => {
    const page: number = 1.2
    const limit: number = 1.2
    return expect(instance.applicationsControllerFindAllV1(page, limit, {})).resolves.toBe(null)
  })
  test("applicationsControllerFindMineV1", () => {
    const page: number = 1.2
    const limit: number = 1.2
    return expect(instance.applicationsControllerFindMineV1(page, limit, {})).resolves.toBe(null)
  })
  test("applicationsControllerFindOneV1", () => {
    const id: string = "id_example"
    return expect(instance.applicationsControllerFindOneV1(id, {})).resolves.toBe(null)
  })
  test("applicationsControllerRemoveV1", () => {
    const id: string = "id_example"
    return expect(instance.applicationsControllerRemoveV1(id, {})).resolves.toBe(null)
  })
  test("applicationsControllerUpdateV1", () => {
    const body: api.UpdateApplicationDto = undefined
    const id: string = "id_example"
    return expect(instance.applicationsControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

describe("AuthApi", () => {
  let instance: api.AuthApi
  beforeEach(function() {
    instance = new api.AuthApi(config)
  });

  test("authControllerLoginV1", () => {
    const body: api.LoginDto = undefined
    return expect(instance.authControllerLoginV1(body, {})).resolves.toBe(null)
  })
})

describe("CompaniesApi", () => {
  let instance: api.CompaniesApi
  beforeEach(function() {
    instance = new api.CompaniesApi(config)
  });

  test("companiesControllerGetV1", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.companiesControllerGetV1(id, {})).resolves.toBe(null)
  })
  test("companiesControllerListV1", () => {
    const page: number = 56
    const per_page: number = 56
    const search: string = "search_example"
    return expect(instance.companiesControllerListV1(page, per_page, search, {})).resolves.toBe(null)
  })
  test("companiesControllerUpdateMeV1", () => {
    const body: api.UpdateCompanyDto = undefined
    return expect(instance.companiesControllerUpdateMeV1(body, {})).resolves.toBe(null)
  })
  test("companiesControllerUpdateV1", () => {
    const body: api.UpdateCompanyDto = undefined
    const id: string = "id_example"
    return expect(instance.companiesControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

describe("ExperiencesApi", () => {
  let instance: api.ExperiencesApi
  beforeEach(function() {
    instance = new api.ExperiencesApi(config)
  });

  test("experiencesControllerCreateForV1", () => {
    const body: api.CreateExperienceDto = undefined
    const student_id: string = "student_id_example"
    return expect(instance.experiencesControllerCreateForV1(body, student_id, {})).resolves.toBe(null)
  })
  test("experiencesControllerCreateV1", () => {
    const body: api.CreateExperienceDto = undefined
    return expect(instance.experiencesControllerCreateV1(body, {})).resolves.toBe(null)
  })
  test("experiencesControllerListForV1", () => {
    const student_id: string = "student_id_example"
    const page: number = 56
    const per_page: number = 56
    return expect(instance.experiencesControllerListForV1(student_id, page, per_page, {})).resolves.toBe(null)
  })
  test("experiencesControllerListV1", () => {
    const page: number = 56
    const per_page: number = 56
    return expect(instance.experiencesControllerListV1(page, per_page, {})).resolves.toBe(null)
  })
  test("experiencesControllerSingleV1", () => {
    const experience_id: number = 56
    return expect(instance.experiencesControllerSingleV1(experience_id, {})).resolves.toBe(null)
  })
  test("experiencesControllerUpdateV1", () => {
    const body: api.UpdateExperienceDto = undefined
    const experience_id: number = 1.2
    return expect(instance.experiencesControllerUpdateV1(body, experience_id, {})).resolves.toBe(null)
  })
})

describe("FormationsApi", () => {
  let instance: api.FormationsApi
  beforeEach(function() {
    instance = new api.FormationsApi(config)
  });

  test("formationsControllerCreateForV1", () => {
    const body: api.CreateFormationDto = undefined
    const student_id: string = "student_id_example"
    return expect(instance.formationsControllerCreateForV1(body, student_id, {})).resolves.toBe(null)
  })
  test("formationsControllerCreateV1", () => {
    const body: api.CreateFormationDto = undefined
    return expect(instance.formationsControllerCreateV1(body, {})).resolves.toBe(null)
  })
  test("formationsControllerListForV1", () => {
    const student_id: string = "student_id_example"
    const page: number = 56
    const per_page: number = 56
    return expect(instance.formationsControllerListForV1(student_id, page, per_page, {})).resolves.toBe(null)
  })
  test("formationsControllerListV1", () => {
    const page: number = 56
    const per_page: number = 56
    return expect(instance.formationsControllerListV1(page, per_page, {})).resolves.toBe(null)
  })
  test("formationsControllerSingleV1", () => {
    const formation_id: number = 56
    return expect(instance.formationsControllerSingleV1(formation_id, {})).resolves.toBe(null)
  })
  test("formationsControllerUpdateV1", () => {
    const body: api.UpdateFormationDto = undefined
    const formation_id: number = 1.2
    return expect(instance.formationsControllerUpdateV1(body, formation_id, {})).resolves.toBe(null)
  })
})

describe("JobsApi", () => {
  let instance: api.JobsApi
  beforeEach(function() {
    instance = new api.JobsApi(config)
  });

  test("jobsControllerApplicationsV1", () => {
    const job_id: string = "job_id_example"
    return expect(instance.jobsControllerApplicationsV1(job_id, {})).resolves.toBe(null)
  })
  test("jobsControllerCreateForCompanyV1", () => {
    const body: api.CreateJobDto = undefined
    return expect(instance.jobsControllerCreateForCompanyV1(body, {})).resolves.toBe(null)
  })
  test("jobsControllerCreateV1", () => {
    const body: api.CreateJobDto = undefined
    const company_id: string = "company_id_example"
    return expect(instance.jobsControllerCreateV1(body, company_id, {})).resolves.toBe(null)
  })
  test("jobsControllerFindAllV1", () => {
    const page: number = 1.2
    const limit: number = 1.2
    const search: string = "search_example"
    const company_id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.jobsControllerFindAllV1(page, limit, search, company_id, {})).resolves.toBe(null)
  })
  test("jobsControllerFindOneV1", () => {
    const job_id: string = "job_id_example"
    return expect(instance.jobsControllerFindOneV1(job_id, {})).resolves.toBe(null)
  })
  test("jobsControllerRemoveV1", () => {
    const id: string = "id_example"
    const job_id: string = "job_id_example"
    return expect(instance.jobsControllerRemoveV1(id, job_id, {})).resolves.toBe(null)
  })
  test("jobsControllerUpdateV1", () => {
    const body: api.UpdateJobDto = undefined
    const job_id: string = "job_id_example"
    return expect(instance.jobsControllerUpdateV1(body, job_id, {})).resolves.toBe(null)
  })
})

describe("ManagedApi", () => {
  let instance: api.ManagedApi
  beforeEach(function() {
    instance = new api.ManagedApi(config)
  });

  test("managedControllerGetV1", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.managedControllerGetV1(id, {})).resolves.toBe(null)
  })
  test("managedControllerListV1", () => {
    const page: number = 56
    const per_page: number = 56
    const author_id: string = "author_id_example"
    const search: string = "search_example"
    return expect(instance.managedControllerListV1(page, per_page, author_id, search, {})).resolves.toBe(null)
  })
  test("managedControllerUpdateV1", () => {
    const body: api.UpdateManagedDto = undefined
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.managedControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

describe("SkillsApi", () => {
  let instance: api.SkillsApi
  beforeEach(function() {
    instance = new api.SkillsApi(config)
  });

  test("skillsControllerApplyV1", () => {
    const id: number = 1.2
    const student_id: Uuid = undefined
    return expect(instance.skillsControllerApplyV1(id, student_id, {})).resolves.toBe(null)
  })
  test("skillsControllerFindV1", () => {
    const id: number = 1.2
    return expect(instance.skillsControllerFindV1(id, {})).resolves.toBe(null)
  })
  test("skillsControllerGetV1", () => {
    const page: number = 56
    const per_page: number = 56
    const name: string = "name_example"
    const type: string = "type_example"
    return expect(instance.skillsControllerGetV1(page, per_page, name, type, {})).resolves.toBe(null)
  })
  test("skillsControllerRemoveV1", () => {
    const id: number = 1.2
    const student_id: Uuid = undefined
    return expect(instance.skillsControllerRemoveV1(id, student_id, {})).resolves.toBe(null)
  })
  test("skillsControllerUpsertV1", () => {
    const body: api.CreateSkillDto = undefined
    const student_id: Uuid = undefined
    return expect(instance.skillsControllerUpsertV1(body, student_id, {})).resolves.toBe(null)
  })
})

describe("StudentsApi", () => {
  let instance: api.StudentsApi
  beforeEach(function() {
    instance = new api.StudentsApi(config)
  });

  test("studentsControllerGetV1", () => {
    const id: string = "38400000-8cf0-11bd-b23e-10b96e4ef00d"
    return expect(instance.studentsControllerGetV1(id, {})).resolves.toBe(null)
  })
  test("studentsControllerListV1", () => {
    const page: number = 56
    const per_page: number = 56
    const search: string = "search_example"
    return expect(instance.studentsControllerListV1(page, per_page, search, {})).resolves.toBe(null)
  })
  test("studentsControllerUpdateMeV1", () => {
    const body: api.UpdateStudentDto = undefined
    return expect(instance.studentsControllerUpdateMeV1(body, {})).resolves.toBe(null)
  })
  test("studentsControllerUpdateV1", () => {
    const body: api.UpdateStudentDto = undefined
    const id: string = "id_example"
    return expect(instance.studentsControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

describe("TagsApi", () => {
  let instance: api.TagsApi
  beforeEach(function() {
    instance = new api.TagsApi(config)
  });

  test("tagsControllerCreateV1", () => {
    const body: api.CreateTagDto = undefined
    return expect(instance.tagsControllerCreateV1(body, {})).resolves.toBe(null)
  })
  test("tagsControllerFindAllV1", () => {
    const limit: any = undefined
    const page: any = undefined
    const search: string = "search_example"
    return expect(instance.tagsControllerFindAllV1(limit, page, search, {})).resolves.toBe(null)
  })
  test("tagsControllerFindOneV1", () => {
    const id: number = 1.2
    return expect(instance.tagsControllerFindOneV1(id, {})).resolves.toBe(null)
  })
  test("tagsControllerRemoveFromJobV1", () => {
    const id: number = 1.2
    const job_id: number = 1.2
    return expect(instance.tagsControllerRemoveFromJobV1(id, job_id, {})).resolves.toBe(null)
  })
  test("tagsControllerUpdateV1", () => {
    const body: api.UpdateTagDto = undefined
    const id: number = 1.2
    return expect(instance.tagsControllerUpdateV1(body, id, {})).resolves.toBe(null)
  })
})

