name: Generate sdk from api
on:
  # On user trigger
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        required: true
        description: The branch in the api repository that contains the swagger implementation
  # On external trigger
  workflow_call:
    inputs:
      branch:
        type: string
        default: main
        required: true
        description: The branch in the api repository that contains the swagger implementation
  # On workflow file changes
  push:
    branches:
      - main

env:
  API_REPOSITORY: Fyn-JobBoard/api
  API_BRANCH: ${{inputs.branch || 'main'}}
  FAKE_APP_PORT: 3000

jobs:
  check-version:
    name: Verify versions
    runs-on: ubuntu-slim
    outputs:
      same_version: ${{steps.incomming.outputs.VERSION == steps.current.outputs.VERSION}}
      target_version: ${{steps.incomming.outputs.VERSION}}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - id: current
        run: |
          if [ -f "./package.json" ];
          then
            echo "VERSION=$(jq .version -r ./package.json)" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v6
        with:
          repository: ${{env.API_REPOSITORY}}
          ref: ${{env.API_BRANCH}}
      - id: incomming
        run: |
          if [ -f "./package.json" ];
          then
            echo "VERSION=$(jq .version -r ./package.json)" >> $GITHUB_OUTPUT
          fi

  generate-sdk:
    name: Generate the sdk for version ${{needs.check-version.outputs.target_version}}
    needs: check-version
    runs-on: ubuntu-latest
    if: ! needs.check-version.outputs.same_version
    services:
      docker:
        image: swaggerapi/swagger-codegen-cli
        ports:
          - $FAKE_APP_PORT:$FAKE_APP_PORT
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{env.API_REPOSITORY}}
          ref: ${{env.API_BRANCH}}

      - name: Setup env variables
        uses: cardinalby/export-env-action@v2
        with:
          # Exists in the api repository
          envFile: ".github/workflows/ci.env"
          expand: true
          export: true

      # Used for postgres to access it
      - name: Generate en_US.UTF-8 locale
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - name: Setup a postgres db
        uses: ikalnytskyi/action-setup-postgres@v8
        with:
          database: ${{ env.DB_DATABASE }}
          password: ${{ env.DB_PASSWORD }}
          username: ${{ env.DB_USERNAME }}
          port: ${{ env.DB_PORT }}

      - name: Installing bun
        uses: oven-sh/setup-bun@v2

      - name: Installing deps
        run: bun install

      - name: Launch API
        env:
          APP_PORT: ${{env.FAKE_APP_PORT}}
        run: bun start & sleep 2

      - name: Debug SDK
        run: |
          curl http://localhost:${{env.FAKE_APP_PORT}}/docs-yaml

      - name: Generates sdk
        uses: bjerkio/swagger-codegen-action@master
        with:
          args: generate
            -i "http://localhost:${{env.FAKE_APP_PORT}}/docs-json"
            -o sdk
            -l typescript-node

      - name: Exporting sdk to ${{needs.check-version.outputs.target_version}}
        uses: ad-m/github-push-action@master
        with:
          branch: v${{needs.check-version.outputs.target_version}}
          directory: sdk
