name: Generate sdk from api
on:
  # On user trigger
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: main
        required: true
        description: The branch in the api repository that contains the swagger implementation
  # On external trigger
  workflow_call:
    inputs:
      branch:
        type: string
        default: main
        required: true
        description: The branch in the api repository that contains the swagger implementation
  # On workflow file changes
  push:
    branches:
      - main

env:
  API_REPOSITORY: Fyn-JobBoard/api
  API_BRANCH: ${{inputs.branch || 'main'}}
  FAKE_APP_PORT: 3000

jobs:
  check-version:
    name: Verify versions
    runs-on: ubuntu-slim
    outputs:
      same_version: ${{steps.incomming.outputs.VERSION == steps.current.outputs.VERSION}}
      target_version: ${{steps.incomming.outputs.VERSION}}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - name: Check latest current version
        id: current
        run: |
          if [ -f "./package.json" ];
          then
            echo "VERSION=$(jq .version -r ./package.json)" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v6
        with:
          repository: ${{env.API_REPOSITORY}}
          ref: ${{env.API_BRANCH}}
      - name: Check incomming version
        id: incomming
        run: |
          if [ -f "./package.json" ];
          then
            echo "VERSION=$(jq .version -r ./package.json)" >> $GITHUB_OUTPUT
          fi

  generate-sdk:
    name: Generate the sdk for version ${{needs.check-version.outputs.target_version}}
    needs: check-version
    runs-on: ubuntu-latest
    permissions: write-all
    if: ! needs.check-version.outputs.same_version
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{env.API_REPOSITORY}}
          ref: ${{env.API_BRANCH}}
          path: api

      - name: Setup env variables
        uses: cardinalby/export-env-action@v2
        with:
          # Exists in the api repository
          envFile: "api/.github/workflows/ci.env"
          expand: true
          export: true

      - name: Setup a postgres db
        uses: ikalnytskyi/action-setup-postgres@v8
        with:
          database: ${{ env.DB_DATABASE }}
          password: ${{ env.DB_PASSWORD }}
          username: ${{ env.DB_USERNAME }}
          port: ${{ env.DB_PORT }}

      - name: Installing bun
        uses: oven-sh/setup-bun@v2

      - name: Launching API
        run: |
          cd api
          bun install
          bun start &
          echo "API_PID=$!" >> $GITHUB_ENV
          sleep 1

      - name: Fetch the Swagger Document
        run: |
          curl -f api.yaml http://localhost:${{env.FAKE_APP_PORT}}/docs-yaml
          curl -fso api.json http://localhost:${{env.FAKE_APP_PORT}}/docs-json

      - name: Stop API and prepare for SDK generation
        run: |
          kill $API_PID
          rm -rf api
          mkdir sdk

      - name: Generates sdk
        uses: johan-jnn/swagger-codegen-v3-action@master
        with:
          args: 'generate
            -i ./api.json
            -o sdk
            -l typescript-fetch
            --release-note "API Version: ${{needs.check-version.outputs.target_version}}"'

      - name: Ensure sdk has been generated
        run: |
          test -n "$(ls -A sdk)"

      - name: Fetch templates
        uses: actions/checkout@v6
        with:
          ref: main
          clean: false
          path: templates
          sparse-checkout: |
            .github/workflows/templates

      - name: Clean templates folder
        run: |
          mv templates/{.github/workflows/templates/*,.}
          rm -rf templates/.github

      - name: Create the package.json file
        run: |
          jq '. += {"version":"${{needs.check-version.outputs.target_version}}"}' templates/package.json > sdk/package.json

      - name: Exporting sdk to branch ${{needs.check-version.outputs.target_version}}
        if: needs.check-version.outputs.target_version != 'main'
        run: |
          cd sdk
          git init -b ${{needs.check-version.outputs.target_version}}
          git remote add origin ${{github.repositoryUrl}}

          git config user.email ${{github.actor_id}}+${{github.actor}}@users.noreply.github.com
          git config user.name ${{github.actor}}

          git add .
          git commit -m "Updating sdk version to ${{needs.check-version.outputs.target_version}}"
          git push origin ${{needs.check-version.outputs.target_version}}
