name: Generate the versions.md file

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  generate:
    name: Generate the versions.md file
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: List branches
        env:
          GITHUB_REPOSITORY_URL: ${{github.server_url}}/${{github.repository}}
        run: ./.github/workflows/scripts/gen_versions.md.sh .github/workflows/templates/versions.md versions.md

      - name: Push modifications
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
